# Generated by Django 4.0.4 on 2022-05-15 11:54

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.CharField(default=backend.models.set_unique_code_book, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=36)),
                ('info', models.CharField(max_length=400)),
                ('genre', models.CharField(max_length=16)),
                ('image', models.CharField(max_length=36)),
            ],
        ),
    ]
